name: neto_app
description: "NETO Budget app"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.4
  flutter_localizations: 
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  flutter_gen: ^5.12.0
  google_fonts: ^6.3.2
  table_calendar: ^3.2.0
  flutter_animate: ^4.5.2
  hugeicons: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logos/


 
